### PR TITLE
added a custom 500 error page

### PR DESCRIPTION
**Pull request by ibnsultan**
modifying the file shoulbe disabled by default
debug option true | false ln 113
if debug is true ?  dump off the error log : show a normal html 500 error page

### CODE REVIEW

**Comment by Lokaci** [comment]
Not working
I downloaded the files but can't get it to work
Not recognizing '\' error for \php_error\reportErrors();
Any suggestions

**Comment by ibnsultan** [comment]
did u get the path correctly

**Comment by Lokaci** [comment]
Yes

**Comment by ibnsultan** [comment]
does the error handler work when you use the original rep, if it does just the original one, just include the 500 error page and the paste the code to identify whether debug is enabled or not

**Comment by Lokaci** [comment]
No it didn't work at all and that's what am confused 😕

**Comment by ibnsultan** [comment]
there could be a conflict with some of your codes or PHP version, try to use [whoops](https://github.com/filp/whoops), if you're looking for a more collective tool I would suggest you take a look at [dyf](https://github.com/ibnsultan/dyf)

**Comment by Lokaci** [comment]
Will do Insha Allah. Thank you so much 🙏

**Pull request closed without merging**
